locallibrary/catalog/urls.py
from django.urls import path,re_path
from django.views.generic import RedirectView
from catalog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:page>', views.listing, name='books-by-page'),
    path('books.json', views.listing_api, name='list-books-api'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name="authors_detail"),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path(r'allbooks/', views.LoanedBooksForLIbraryans.as_view(), name="allbooks-borrowed"),
    path('book/<uuid:pk>/renew/', views.RenewBookView.as_view(), name='renew-book-librarian'), # pq n usar o (?P<pk>\d+)?
    # como exatamente essa pk vai receber um valor? ja na view?
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name="book-create"),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name="book-update"),
    path('book/<int:pk>/delete', views.BookDelete.as_view(), name="book-delete"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Use static() to add url mapping to serve static files during development (only)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name
    
class Language(models.Model):
    name = models.CharField(max_length=100, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)

    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")

    isbn = models.CharField('ISBN', max_length=13, help_text="13 Character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN</a>")

    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']
    
    def display_genre(self):
        return ','. join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])   

    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')

    book = models.ForeignKey('Book', on_delete=models.RESTRICT, 
    null=True)

    imprint = models.CharField(max_length=200)
    
    due_back = models.DateField(null=True, blank=True)

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintence'),
        ('o', 'On loan'),
        ('a', 'Avaiable'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering=['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'({self.id})({self.book.title})'
    
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)
    
    def overdue_today(self):
        return bool(self.due_back and date.today() == self.due_back)
    

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True) 

    class Meta: 
        ordering=['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('authors_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}' 

  

locallibrary/catalog/forms.py
from catalog.models import BookInstance, Author, Book, Genre, Language
from django import forms

from django.core.exceptions import ValidationError

from django.utils.translation import gettext_lazy as _
import datetime





# class RenewBookForm(forms.Form):
#     renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

#     def clean_renewal_date(self):
#         data = self.cleaned_data['renewal_date']

#         # Check if a date is not in the past.
#         if data < datetime.date.today():
#             raise ValidationError(_('Invalid date - renewal in past'))

#         # Check if a date is in the allowed range (+4 weeks from today).
#         if data > datetime.date.today() + datetime.timedelta(weeks=4):
#             raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

#         # Remember to always return the cleaned data.
#         return data


class RenewBookModelForm(forms.ModelForm):

    # def clean_due_back(self):
    #     data = self.cleaned_data['due_back']

    #     if data < datetime.date.today():
    #         raise ValidationError(_('Invalid date - renewal in past'))
        
    #     if data > datetime.date.today() + datetime.timedelta(weeks=4):
    #         raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
    #     return data

    def set_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data
    
    class Meta:
        model = BookInstance
        fields = ['due_back']
        widgets = {
            'due_back': forms.DateInput(attrs={'class': 'form-control form-control-rounded mb-2'})
        }
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

class CreateAuthorForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Primeiro Nome', 'class': 'form-control form-control-rounded mb-2'}
    ))

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Segundo Nome', 'class': 'form-control form-control-rounded mb-2'}
    ))

    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'form-control form-control-rounded mb-2'}
    ))

    date_of_death = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'form-control form-control-rounded mb-2'}
    ))

    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
        

class CreateBookForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Titulo', 'class': 'form-control form-control-rounded mb-2'}
    ))

    summary = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'Description of the book', 'class': 'form-control form-control-rounded mb-2', 'rows': '2'}
    ))

    isbn = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': '13 character ISBN', 'class': 'form-control form-control-rounded mb-2'}
    ))

    author = forms.ModelChoiceField(
        queryset= Author.objects.all(),
        to_field_name='first_name',
        required=True,  
        widget=forms.Select(attrs={'class': 'form-control form-control-rounded mb-2'})
    )

    genre = forms.ModelChoiceField(
        queryset= Genre.objects.all(),
        to_field_name='name',
        required=True,  
        widget=forms.Select(attrs={'class': 'form-control form-control-rounded mb-2'})
    )

    language = forms.ModelChoiceField(
        queryset= Language.objects.all(),
        to_field_name='name',
        required=True,  
        widget=forms.Select(attrs={'class': 'form-control form-control-rounded mb-2'})
    )

    class Meta:
        model = Book
        fields = ['title', 'summary', 'isbn', 'author', 'language', 'genre']

locallibrary/catalog/views.py
import datetime

from catalog.models import Book, Author, BookInstance, Author
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django.core.paginator import Paginator

from catalog.forms import *

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy



def BASE(request):
    return render(request, 'base.html')

def index(request):

    num_books = Book.objects.all(). count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genre_romance = Book.objects.all().filter(genre = 1).count()
    num_borrowed_books = BookInstance.objects.all().filter(status__exact='o').count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    request.session.modified = True

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
        'num_borrowed_books': num_borrowed_books
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    paginate_by = 3

    queryset = Book.objects.all().order_by('title')
    #a query retorna uma lista? isso é um método slicing?

    template_name = 'book_list.html'

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)

        return context

def listing(request, page):
        books = Book.objects.all()
        paginator = Paginator(books, per_page=3)
        page_object = paginator.get_page(page)
        context = {"page_obj": page_object}
        return render(request, "catalog/book_list.html", context)

def listing_api(request):
    page_number = request.GET.get("page", 1)
    per_page = request.GET.get("per_page", 3)
    startswith = request.GET.get("startswith", "")
    books = Book.objects.filter(
        title__startswith=startswith
    )
    paginator = Paginator(books, per_page)
    page_obj = paginator.get_page(page_number)
    data = [{"title": book.title} for book in page_obj.object_list ]

    payload = {
        "page": {
            "current": page_obj.number,
            "has_next": page_obj.has_next(),
            "has_previous": page_obj.has_previous()
        },
        "data": data
    }

    return JsonResponse(payload)

class BookDetailView(generic.DetailView):

    model = Book
    template_name = 'catalog/book_detail.html'

class AuthorListView(generic.ListView):
    model: Author
    paginate_by = 10

    queryset = Author.objects.all()
    context_object_name = 'author_list'

class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 4


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
        )


class LoanedBooksForLIbraryans(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_libraryans.html'
    paginate_bt = 10


    def get_queryset(self):
        return (
            BookInstance.objects.filter(status__exact='o').order_by('due_back')
        )


class RenewBookView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    permission_required = 'catalog.can_mark_returned'
    form_class = RenewBookModelForm


    def get(self, request, pk):
        book_instance = get_object_or_404(BookInstance, pk=pk)
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm({'due_back': proposed_renewal_date})

        context = {
            'form': form,
            'book_instance': book_instance
        }

        ##return render(reverse(request, 'catalog/book_renew_librarian.html', context))
        return render(request, 'catalog/book_renew_librarian.html', context)
        ##return HttpResponseRedirect(reverse('catalog/book_renew_librarian.html', context))

    def post(self, request, pk):

        book_instance = get_object_or_404(BookInstance, pk=pk)
        form = RenewBookModelForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            return render(request, 'catalog/book_renew_librarian.html', context) ##HttpResponseRedirect redireciona 
        ##pra uma URL especifica e o reverse() cria uma url a partir do nome de url setado la na urls.py
        
        else:
            context = {
                'form': form,
                'book_instance': book_instance,
            }

            return render(request, 'catalog/book_renew_librarian.html', context)
      

class AuthorCreateView(PermissionRequiredMixin, CreateView):
    model = Author
    permission_required = 'catalog.create_author'
    template_name = 'catalog/author_form.html'
    form_class = CreateAuthorForm

    

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = '__all__'
    permission_required = 'catalog.change_author'
    success_url = reverse_lazy('authors')

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("author-delete", kwargs={"pk": self.object.pk})
            )
        
class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    permission_required = 'catalog.add_book'
    template_name = 'catalog/book_form.html'
    form_class = CreateBookForm

    def post(self, request):

        form = CreateBookForm(request.POST)

        if form.is_valid(): 
            title = form.cleaned_data['title']
            language = form.cleaned_data['language']
            print(language)
            id_language = Language.objects.get(name=language)

            language = id_language
            

            language.save()

            context = {
                'form': form
            }

            return render(request, 'catalog/book_detail.html', context)
        
        else:
            context = {
                'form': form
            }

            return render(request, 'catalog/book_renew_librarian.html', context)

class  BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.change_book'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required = 'catalog.delete_book'
    success_url = reverse_lazy('books')
    

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Author: {{ author }}</h1>

    {% if author.book_set.all %}

        <p>You can't delete this author until all their books have been deleted:</p>

        <ul>
            {% for book in author.book_set.all %}
                <li>
                    <a href="{% url 'book-detail' book.pk %}">{{ book }}</a>
                    ({{book.bookinstance_set.all.count}})
                </li>
            {% endfor %}
        </ul>

    {% else%}

        <p>Are you sure you want to delete the author?</p>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete.">
        </form>

    {% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block title %}
    Author {{ author.last_name}}, {{ author.first_name }}
{% endblock %}

{% block buttons %}

    {% if perms.catalog.change_author or perms.catalog.delete_author %}
        {% if perms.catalog.change_author %}

            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                <a href="{% url 'author-update' author.id %}" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
                    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                    Update Author
                </a>
                </div>
            </div>

        {% endif %}

        {% if perms.catalog.chenge_author %}

            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                <a href="{% url 'author-delete' author.id %}" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
                    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                    Delete Author
                </a>
                </div>
            </div>

        {% endif %}
    {% endif %}



{% endblock %}

{% block content %}
    <h1>Author: {{ author.last_name}}, {{ author.first_name}} </h1>
    <p>{% if author.date_of_birth %}{{ author.date_of_birth}}{% endif %} - {% if author.date_of_death %} {{ author.date_of_death}}{% endif %}</p>

    {% if author.book_set.all %}
        <p><strong>Books</strong></p>
        {% for book in author.book_set.all %}
            <h5><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.id }})</h5>
            <p>{{ book.summary }}</p>
        {% endfor %}
    {% else%}
        <p>There is no book of this author registered</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base.html" %}

{% block content %}

{% block buttons %}
{% endblock %}
<script>
  document.getElementById('id_first_name');
</script>
<div class="col-md-6">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">
        {% block title %}
         Author Form
         {% endblock %}
      </h3>
      <div class="mb-3">
        <form action="" method="post">
          {% csrf_token %}

          <p>{{ form.as_p }}</p>
          <div class="row align-items-center">
            <div class="col"></div>
            <div class="col-auto">
              <input type="submit" value="Salvar" class="btn btn-primary">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete: {{ book }}</h1>

    {% if book.bookinstance_set.all %}
        <p>You can't delete this book until all their book instance have been deleted:</p>

        <ul>
            {% for bookinst in book.bookinstance_set.all %}

                <li>
                    <a href="{% url 'book-detail' bookinst.book.pk  %}">{{ bookinst.book.title}}</a>
                    ({{ bookinst.due_back}}) {% if user.is_staff %} - {{ bookinst.borrower }} {% endif %}
                </li>
            {% endfor %}
        </ul>
    
        {% else %}
            <p>Are you sure you want to delete this book?</p>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes, delete">
            </form>
        
        {% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}
    {{ book.title }}
{% endblock %}
{% block buttons %}

    {% if perms.catalog.change_book or perms.catalog.delete_book %}
        {% if perms.catalog.change_author%}

            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                <a href="{% url 'book-update' book.pk %}" class="btn btn-primary d-none d-sm-inline-block" >
                    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                    Update Book
                </a>
                </div>
            </div>

        {% endif %}
        {% if perms.catalog.delete_autor %}

            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                <a href="{% url 'book-delete' book.id %}" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
                    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                    Delete Book
                </a>
                </div>
            </div>
        {% endif %}
      
    {% endif %}

    {% endblock %}


{% block content %}
    <h1>Title {{book.title}}</h1>

    <p><strong>Author:</strong><a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong>{{ book.summary }}</p>
    <p><strong>ISBN:</strong>{{ book.isbn }}</p>
    <p><strong>Language:</strong>{{ book.language }}</p>
    <p><strong>Genre:</strong>{{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px; margin-top:20px">
        <h4>Copies</h4>
        {% if  book.bookinstance_set.all %}
            {% for copy in book.bookinstance_set.all %}
                <hr>
                <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                    {{ copy.get_status_display }}
                </p>
                {% if copy.status != 'a' %}
                    <p><strong>Due to be returned:</strong>{{ copy.due_back }}</p>
                {% endif %}

                <p><strong>Imprint:</strong>{{ copy.imprint }}</p>
                <p class="text-muted"><strong>Id:</strong> {{ copy.id }} </p>
            {% endfor %}
        {% else %}
        <hr>
        <p>Nenhum status cadastrado para o livro</p>
        {% endif %}
    </div>

    {% block modal %}



    {% endblock %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_libraryans.html
{% extends 'base.html' %}

{% block content %}
    <h1>All Borrowed Books </h1>

    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list%}
        <li class="{% if bookinst.is_overdue %}text-danger{% elif bookinst.is_overdue %}text-warning{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title}}</a>
            ({{ bookinst.due_back}}) {% if user.is_staff %} - {{ bookinst.borrower }} {% endif %}{% if perms.catalog.can_mark_returned %} - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a> {% endif %}
        </li>
        {% endfor %}
    </ul>

    {% else %}

    <p>There is no books borrowed.</p>

    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>
    {% if bookinstance_list %}
            <div class="page-body">
                <div class="container-xl">
                    <div class="row row-cards">
                        <div class="row row-cards row-deck">
                            {% for bookinst in bookinstance_list %}

                            
                                
                                <div class="col-md-4">
                                    <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title"><a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a></h3>
                                    </div>
                                    <div class="card-footer">
                                        <p class="{% if bookinst.is_overdue %}text-dange{% elif bookinst.overdue_today %}text-warning{% endif %}">
                                            ({{ bookinst.due_back }})
                                        </p>
                                        
                                    </div>
                                    </div>
                                </div>

                            {% comment %} <div class="col-md-6 col-lg-3">
                                <div class="card">
                                <div class="img-responsive img-responsive-21x9 card-img-top" style="background-image: url(./static/photos/home-office-desk-with-macbook-iphone-calendar-watch-and-organizer.jpg)"></div>
                                <div class="card-body">
                                    <h3 class="card-title"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h3>
                                    <p class="text-muted">({{book.author}})</p>
                                </div> {% endcomment %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
    {% else %}
        <div class="col-lg-4">
            <div class="card">
            <div class="empty">
                <div class="empty-img"><img src="" height="128" alt="">
                </div>
                <p class="empty-title">No results found</p>
                <p class="empty-subtitle text-muted">
                    There are no books borrowed..
                </p>
                <div class="empty-action">
                    <div class="btn-list">
                        <a href="#" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
                        <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                        Renew a Book.
                        </a>
                    </div>
                </div>
            </div>
            </div>
        </div>
    {% endif %}

{% endblock %}